version: "3.7"
services:
  gitlab:
    image: gitlab/gitlab-ee:latest
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2048M
    ports:
      - "22:22"
      - "80:80"
      - "443:443"
    volumes:
      - gitlab-data-opt:/var/opt/gitlab
      - gitlab-data-log:/var/log/gitlab
      - gitlab-data-etc:/etc/gitlab
    shm_size: '256m'
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    configs:
      - source: gitlab
        target: /omnibus_config.rb
    secrets:
      - gitlab_root_password

configs:
  gitlab:
    file: ./gitlab.rb
secrets:
  gitlab_root_password:
    file: ./root_password.txt

volumes:
  gitlab-data-opt:
  gitlab-data-log:
  gitlab-data-etc: