version: "3.6"
services:
  gitlab:
    image: gitlab/gitlab-ee:latest
    ports:
      - "22:22"
      - "80:80"
      - "443:443"
    volumes:
      - gitlab-data-opt:/var/opt/gitlab
      - gitlab-data-log:/var/log/gitlab
      - gitlab-data-etc:/etc/gitlab
    shm_size: '256m'
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    configs:
      - source: gitlab
        target: /omnibus_config.rb
    secrets:
      - gitlab_root_password
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab-data-runner:/etc/gitlab-runner
    deploy:
      mode: replicated
      replicas: 4
  
  register-runner:
    restart: 'no'
    image: gitlab/gitlab-runner:alpine
    command:
      - register
      - --non-interactive
      - --locked=false
      - --name=docker-runner
      - --executor=docker
      - --url "http://gitlab/" 
      - --registration-token "PROJECT_REGISTRATION_TOKEN"
      - --description "docker-runner"
      - --access-level="not_protected"
      - --run-untagged="true"
      - --docker-image alpine:latest
    volumes:
      - gitlab-data-runner:/etc/gitlab-runner
      
configs:
  gitlab:
    file: ./gitlab.rb
secrets:
  gitlab_root_password:
    file: ./root_password.txt

volumes:
 gitlab-data-runner:
 gitlab-data-opt:
 gitlab-data-log:
 gitlab-data-etc: