version: "3.7"
services:
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab-data-runner:/etc/gitlab-runner
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
volumes:
  gitlab-data-runner: { }
